website = "http://www.salihalgul.com"
course = "Python Kursu: Baştan sona Python programlama öğreniyorum."

message = " Hello World "
message = message.strip()
print(message)
result = " Hello World ".strip()
print(result)
result = " Hello World ".lstrip()
print(result)
result = " Hello World ".rstrip()
print(result)
result = website.lstrip("/:pth")
print(result)
result = "http://www.salihalgul.com".strip("mocpth./:w")
print(result)
result = course.lower()
print(result)
result = course.upper()
print(result)
result = course.title()
print(result)
result = course.count("a", 0, 30)
print(result)
result = website.startswith("http")
print(result)
result = website.endswith("com")
print(result)
result = website.find("com",0,10)
print(result)
result = "Contents".center(50, "*")
print(result)
result = "Content".ljust(50, "*")
print(result)
result = "Content".rjust(50, "*")
print(result)
result = course.replace(" ", "-")
print(result)
result = course.replace(" ", "-", 3)
print(result)
result = course.replace(" ", "")
print(result)
result = "Hello World".replace("World", "There")
print(result)
result = course.split(" ")
print(result)
